POST http://localhost:3000/api/services
Content-Type: application/json

{
    "name": "Algum serviço dois",
    "description": "Alguma descrição dois",
    "price": 3000,
    "image": "https://images.unsplash.com/photo-1478146059778-26028b07395a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=892&q=80"
}

###
GET http://localhost:3000/api/services

###
GET http://localhost:3000/api/services/64ff219263ecd93e82973993

###
DELETE http://localhost:3000/api/services/64ff26662bb353650f35feb5

###
PUT http://localhost:3000/api/services/64ff219263ecd93e82973993
Content-Type: application/json

{
    "name": "Atualização primeiro serviço",
    "description": "Alguma descrição dois atualizado",
    "price": 5000,
    "image": "https://images.unsplash.com/photo-1478146059778-26028b07395a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=892&q=80"
}

###
POST http://localhost:3000/api/parties
Content-Type: application/json

{
    "title": "Meu evento",
    "author": "Alexandre",
    "description": "Uma festa de formatura",
    "budget": 20000,
    "image": "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    "services": [
        {
            "name": "Algum serviço 1",
            "description": "Alguma descrição 1",
            "price": 3000,
            "image": "https://images.unsplash.com/photo-1478146059778-26028b07395a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=892&q=80"
        },
        {
            "name": "Algum serviço 2",
            "description": "Alguma descrição 2",
            "price": 5000,
            "image": "https://images.unsplash.com/photo-1478146059778-26028b07395a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=892&q=80"
        }
    ]
}

###
GET http://localhost:3000/api/parties

###
GET http://localhost:3000/api/parties/64ff523c853df531214ab149

###
DELETE http://localhost:3000/api/parties/64ff5cd4e56187df28b9decf


###
PUT http://localhost:3000/api/parties/64ff523c853df531214ab149
Content-Type: application/json

{
    "title": "Meu evento atualizado",
    "author": "Alexandre Rogério",
    "description": "Uma festa de formatura e de conquista do primeiro emprego",
    "budget": 20000,
    "image": "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    "services": [
        {
            "name": "Algum serviço 1",
            "description": "Alguma descrição 1",
            "price": 3000,
            "image": "https://images.unsplash.com/photo-1478146059778-26028b07395a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=892&q=80"
        },
        {
            "name": "Algum serviço 2",
            "description": "Alguma descrição 2",
            "price": 5000,
            "image": "https://images.unsplash.com/photo-1478146059778-26028b07395a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=892&q=80"
        }
    ]
}
